### ISSUE TITLE
Automatic build of Mars 2020 mission dictionary failed, possibly due to error in LDDTool command

### ISSUE THREAD

**Issue by sslavney** [pds-data-dictionaries/ldd-mars2020#12]
Tried to publish branch "rev-210407" to ldd-m2020. The log file shows that validation failed for various reasons related to the IMG dictionary, which is a dependency of the M2020 dictionary. But I see from line 240 in the log file that the IMG ingest file appears twice on the LDDTool command line:

INFO:pds_github_util.utils.ldd_gen:['bash', '/tmp/lddtool-13.0.0/bin/lddtool', '-lpJ', '-V', '1F00', '/home/runner/work/ldd-m2020/ldd-m2020/src/dependencies/ldd-img/src/PDS4_IMG_IngestLDD.xml', '/home/runner/work/ldd-m2020/ldd-m2020/src/dependencies/ldd-img/src/PDS4_IMG_IngestLDD.xml', '/home/runner/work/ldd-m2020/ldd-m2020/src/PDS4_MARS2020_IngestLDD.xml']

Not sure if this is the cause of the validation failure, but it should be fixed anyway. If the automatic build still fails after this fix, then I'm stumped. By the way, running LDDTool 12.1.0 locally is successful.

Link to log file: https://github.com/pds-data-dictionaries/ldd-m2020/runs/2291496554?check_suite_focus=true

**Comment by jordanpadams** [comment]
@sslavney opened a ticket to track this. looks like LDDTool has a bug in its first test :-) 

https://github.com/NASA-PDS/pds4-information-model/issues/328

**Comment by jordanpadams** [comment]
@sslavney i removed the bad release of LDDTool and re-ran the Github Actions. looks like it ran successfully.
