### ISSUE TITLE
[m2020] update release_number as optional

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/ldd-mars2020#15]
@sslavney We have had a request to allow release_number as optional.

just meaning to set minimum_occurrences = 0 
https://github.com/pds-data-dictionaries/ldd-m2020/blob/ecc19371325663ea9478fde7a21fdcbb708571da/src/PDS4_MARS2020_IngestLDD.xml#L4000

Searching for this in other dictionaries, I find that InSight and MSN release_number are optional also. I'm not sure if M2020 had a stated requirement for this in every label?

**Comment by sslavney** [comment]
@thareUSGS release_number is required but nillable. Could the request be accommodated with 
<release_number xsi:nil="true" nilReason="inapplicable"></release_number>
?

**Comment by rgdeen** [comment]
@sslavney that would break the paradigm used in the entire rest of the label system.  Nillable is only rarely used in the pds4 labels (and correctly so), to indicate places where nil needs to explicitly be indicated.  There is no point in including release_number in every... single... label... when it's inapplicable in most if not all of them.  If it's inapplicable then the label should be absent.. .there's no reason to indicate that it's inapplicable.

Moreover, release_number is not something we can even provide at the time the label source data is created.  We do not - cannot and should not - know what PDS release any given label is going into at the time the data is created in ops.  And the ops label is the source for the PDS label data.  Filling this would require a flag be set on the velocity templates... but that would also prevent us from *ever* creating pds4 labels as we go as part of ops, which is a long-term goal.  For these reasons, release_number is a bad idea - I'd even say a nonstarter - to even include in the label at *all*.  It's not the product's job to indicate what release it's in, it's the release's job to indicate what products are included.  I would strongly urge it be completely eliminated, and we will not be providing it in labels IDS delivers.

Finally, if it was really important to include the release number, it would be not in the mars2020 dictionary but rather the PDS core.  The fact that it's not in PDS core means that it is not considered important to PDS.  Therefore, there is no justification for requiring the label item to be present in the mars2020 dictionary.

@thareUSGS

**Comment by sslavney** [comment]
@rgdeen If it's too hard for IDS to fill out the release number, then let it always be nil with nilReason="inapplicable". Or consider nilReason = "missing", which is more accurate. "missing - The correct value is not readily available to the sender of this data. However, a correct value probably exists."

**Comment by rgdeen** [comment]
@sslavney unfortunately that breaks the paradigm used everywhere else in the label.  If a keyword is intended to be optional, then it needs to be optional.  Nillable is used for exceptional circumstances... not circumstances where it is perfectly normal to be absent.

There is no reason for this attribute to be present in every label when we have no ability to ever fill it in from IDS-provided data.  There are no other instances in the entire DD system - at least not the extensive subset that we use for images - where a keyword such as this is required when it will always be nil.

Please find me a counterexample to show precedent here.

**Comment by nttoole** [comment]
While nil-entries seem to pop up in non-img labels, they are far more rare for img cases.  
And since img will never be including this label, I would agree that its probably best to have this entry be optional.

**Comment by myche** [comment]
Maybe a compromise worth pursuing would be to migrate items such as `release_id` into a new `archive` discipline LDD (or call it something else).  There's loads of useful characteristics that are important to archivists, but not the data provider.  We at PDS know what the `release_id` is (or will be) but the data provider doesn't and, really, shouldn't.  So, let's keep the attribute, but move it to a different LDD that is easily ignored by data providers.

And then, by all means, include all kinds of useful stuff that we archivists might care about.

**Comment by katecrombie** [comment]
Myche's idea is intriguing.  I have a bigger picture question about the whole concept of releaese_id.  I can see Bob's point that a data provider might not know what this number would be. Conversely, that might be the short-hand used for communication between a node and provider, so the attribute means something to the group working on the archive.  I'm not sure a user of the archived data would ever use this attribute as a search term, data collection date or mission phase would more than likely get them what they want.  So, I think my real question is who is using this attribute, and what is its true purpose? If, as Myche suggests, it is an archive-only piece of metadata then maybe some thought needs to be put into the "archive_LDD" or some other construct that allows the nodes to quickly gather the information they need on to do their reporting.

**Comment by jordanpadams** [comment]
As a note to this thread, this is one of many pieces of information we plan on capturing using the Tracking Service, which is used to capture the metadata for tracking the end-to-end lifecycle of a product from peer review certification to delivery by the instrument team to PDS and delivery to NSSDCA. The service is still in the design phase, but it is coming. An LDD to describe this data model would be great for this as well!

**Comment by sslavney** [comment]
OK, I'll make it optional. You win this one, Bob.
