### ISSUE TITLE
Unable to build ldd-mars2020 mission dictionary

### ISSUE THREAD

**Issue by sslavney** [pds-data-dictionaries/ldd-mars2020#18]
I'm unable to build a new version of ldd-mars2020. The error message is "Unable to resolve action `NASA-PDS/gh-action-pds4-ldd@master`, unable to find version `master`". I had already changed the "master" branch name to "main" as instructed. I'm stuck. Need this asap for Mars 2020 validation. Thanks.

**Comment by jordanpadams** [comment]
@sslavney should be fixed. sorry I missed this repo when we updated to use `main` branches

**Comment by jordanpadams** [comment]
@sslavney which branch are you working off of? you may need to [rebase](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch#rebasing-your-project-branch-onto-another-branch) your branch with `main`
