### ISSUE TITLE
ldd-mars2020 Release and Tag LDD Release workflow failed

### ISSUE THREAD

**Issue by sslavney** [pds-data-dictionaries/ldd-mars2020#22]
Release and Tag LDD Release workflow for ldd-mars2020 failed with the following error.

"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 alabaster-0.7.12 babel-2.9.1 beautifulsoup4-4.9.0 certifi-2021.5.30 cffi-1.14.6 chardet-3.0.4 cryptography-3.4.7 deprecated-1.2.12 docutils-0.16 emoji-0.5.0 gitdb-4.0.7 github3.py-2.0.0 gitpython-3.1.0 idna-2.10 imagesize-1.2.0 jwcrypto-0.9.1 lxml-4.6.3 markdown2-2.3.0 mdutils-1.3.1 packaging-21.0 pds-github-util-0.22.2 pycparser-2.20 pygments-2.9.0 pyparsing-2.4.7 pystache-0.5.4 python-dateutil-2.8.2 pytz-2021.1 pyyaml-5.4.1 requests-2.23.0 rstcloth-0.3.1 six-1.16.0 smmap-4.0.0 snowballstemmer-2.1.0 soupsieve-2.2.1 sphinx-3.5.4 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 uritemplate-3.0.1 urllib3-1.25.11 wrapt-1.12.1
pds-github-util 0.22.2 requires packaging==20.9, but you have packaging 21.0 which is incompatible."

https://github.com/pds-data-dictionaries/ldd-mars2020/runs/3146956134?check_suite_focus=true

**Comment by jordanpadams** [comment]
closed per https://github.com/pds-data-dictionaries/ldd-mars2020/pull/24 and f6ca9f5f5a386030b045be0f58308810c2c780d5
