### ISSUE TITLE
Wrong version of IMG dictionary used to build M2020 dictionary

### ISSUE THREAD

**Issue by sslavney** [pds-data-dictionaries/ldd-mars2020#4]
The file PDS4_MARS2020_1E00_1000.xsd is invalid. The error message in Oxygen is "Failed to read schema document 'file:/Z:/stage/pds4/schema/img/v1/PDS4_IMG_1E00_1600.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>." Data product labels that refer to this schema are also invalid.

Line 23 of PDS4_MARS2020_1E00_1000.xsd imports PDS4_IMG_1E00_1600.xsd, but line 15 of the IngestLDD file specifies PDS4_IMG_1E00_1800.xsd. Why was the wrong version used during the automatic build? If line 23 of PDS4_MARS2020_1E00_1000.xsd is corrected manually to read PDS4_IMG_1E00_1800, the file becomes valid, and labels that use this schema become valid. 

I also tried running LDDTool locally to build the MARS2020 dictionary, and got the same error in the XSD file.

**Comment by jordanpadams** [comment]
@sslavney this is a bug in LDDTool. I see the [same issue with the msss cam repo](https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/9976d2c4effa037e7211a65d2fbbe44f1ec5f84e/build/development/575b2e08f4c518d9d5067f1cf76146d6cd713953/1.14.0.0/PDS4_MSSS_CAM_MH_1E00_1000.xsd#L25)

I created a ticket to have @jshughes look into a fix for us. 

https://github.com/NASA-PDS/pds4-information-model/issues/229

**Comment by sslavney** [comment]
This was resolved with LDDTool 12.0.2.
